[package]
name = "Data_analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
polars = { version = "0.43.1", features = ["lazy", "csv"] }
postgres = { version = "0.19", features = ["with-chrono-0_4"] }
